version: "3.8"

services:
  portfolio:
    build:
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    networks:
      - proxymanager_default

networks:
  proxymanager_default:
    external: true